openapi: 3.0.0
info:
  title: Dictionary Backend Server
  description: API for managing a dictionary of animals and user authentication.
  version: 1.0.0
servers:
  - url: http://localhost:3000

paths:
  /lookup/{answers}:
    get:
      summary: Look up an animal based on answers
      parameters:
        - name: answers
          in: path
          required: true
          description: Answers from the questionnaire to process
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved animal information
          content:
            application/json:
              schema:
                type: object
                properties:
                  animal:
                    type: string
                    description: The animal obtained based on answers
        '401':
          description: Unauthorized
      security:
        - cookieAuth: []
  
  /save/:
    post:
      summary: Save an animal to the dictionary
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                animal:
                  type: string
                  description: The animal to save
      responses:
        '200':
          description: Successfully saved animal
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '401':
          description: Unauthorized
      security:
        - cookieAuth: []
  
  /login/:
    get:
      summary: Display the login page
      responses:
        '200':
          description: Login page

  /:
    get:
      summary: Go to home page
      responses:
        '200':
          description: Home page
      security:
        - cookieAuth: []

  /auth/google/:
    get:
      summary: Authenticate with Google
      responses:
        '302':
          description: Redirect to Google for authentication

  /auth/google/callback:
    get:
      summary: Google authentication callback
      responses:
        '302':
          description: Redirect to home on success or login on failure

  /logout:
    post:
      summary: Log out the current user
      responses:
        '302':
          description: Redirect to login page

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: connect.sid
